### ISSUE TITLE
TypeError: TwingateResourceProtocolsArgs._configure() missing 2 required positional arguments: 'tcp' and 'udp'

### ISSUE THREAD

**Issue by xiongchiamiov** [Twingate-Labs/pulumi-twingate#12]
Our CI updated to pulumi-twingate-0.0.47 (Python) and we're now getting this error:

```
        File "/home/runner/work/winfrastructure/winfrastructure/aws/./resources/twingate/twingate_com.py", line 74, in <module>
          twingate.TwingateResource(
        File "/home/runner/work/winfrastructure/winfrastructure/aws/venv/lib/python3.10/site-packages/pulumi_twingate/twingate_resource.py", line 429, in __init__
          __self__._internal_init(resource_name, *args, **kwargs)
        File "/home/runner/work/winfrastructure/winfrastructure/aws/venv/lib/python3.10/site-packages/pulumi_twingate/twingate_resource.py", line 470, in _internal_init
          TwingateResourceProtocolsArgs._configure(_setter, **protocols)
      TypeError: TwingateResourceProtocolsArgs._configure() missing 2 required positional arguments: 'tcp' and 'udp'
```

I think this is caused by 6b4ed2786e6048bd037914efd8e9c2ce6ef187cc, but honestly I can't tell from reading the code what's going wrong there.

FWIW, this particular instance creation of `TwingateResource` is one in which we're not specifying the `protocols` field at all, just leaving it to the default.  I haven't experimented to see if it also errors out when specified.

**Comment by emrul** [comment]
Hi @xiongchiamiov, thank you for reporting this. We will investigate it but in the meantime we would suggest using the previous version of the provider and suggest that the CI/CD process shouldn't update to the latest version automatically in case there are breaking changes.

**Comment by xiongchiamiov** [comment]
Yep, I've pinned the older version now (which we've done with other providers, just missed this one), so no urgency on our part.

**Comment by emrul** [comment]
Thank you, apologies for the issue and we will update the issue as soon as we can.

**Comment by emrul** [comment]
I _think_ this might be an issue with the generated Python code though not absolutely certain. I have raised the problem in an issue [here](https://github.com/pulumi/pulumi/issues/14013).

**Comment by xiongchiamiov** [comment]
Following through the linked issues, it looks like the code gen issue _should_ be fixed in pulumi [3.85.0](https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#3850-2023-09-22).  Again, no rush from my end since the previous version is working just fine, but let me know if you'd like me to test an update.

**Comment by emrul** [comment]
Hi @xiongchiamiov, the issue should indeed be fixed but we have a dependency on [pulumi/pulumi-terraform-bridge](https://github.com/pulumi/pulumi-terraform-bridge/) which is currently not compatible with the fix version of [pulumi/pulumi 3.86.0](https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#3860-2023-09-26) release. The 3.85.0 (that you mentioned in your comment) appears to be the one that is problematic.

We will wait for an updated `pulumi-terraform-bridge` release and then re-try updating.

**Comment by chenbishop** [comment]
@xiongchiamiov apologies for the delay, we have release 0.0.48 and this should fix the issue.
